server:
  port: 0

spring:
  application:
    name: doctor-service

  datasource:
    url: jdbc:mysql://localhost:3306/project
    username: admin
    password: admin

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

  boot:
    admin:
      client:
        url: http://localhost:8888

eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    enabled: false
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include:
        - '*'

logging:
  file: logs/doctor-service.log