server.port: 0

spring:
  application:
    name: appointment-service

  datasource:
    url: jdbc:h2:mem:testDb
    username: test1
    password: test1

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
