server.port: 0

spring:
  application:
    name: enquiry-service

  datasource:
    url: jdbc:h2:mem:testDb
    username: test1
    password: test1
    
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    preferIpAddress: true
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}